name: Databricks Automation

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master

jobs:
  run-databricks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Debug env
        env:
          DATABRICKS_EMAIL: ${{ secrets.DATABRICKS_EMAIL }}
        run: |
          echo "EMAIL=$DATABRICKS_EMAIL"

      - name: Run Databricks automation
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_EMAIL: ${{ secrets.DATABRICKS_EMAIL }}
          DATABRICKS_NOTEBOOK_PATH: ${{ secrets.DATABRICKS_NOTEBOOK_PATH }}
          DATABRICKS_PIPELINE_ID: ${{ secrets.DATABRICKS_PIPELINE_ID }}
        run: |
          python main.py